### ISSUE TITLE
Section Formatting Issue - Wrong Version?

### ISSUE THREAD

**Issue by jrchamp** [openssl/web#46]
Something is wrong with formatting here: https://www.openssl.org/news/openssl-1.1.1-notes.inc that is affecting the HTML version: https://www.openssl.org/news/openssl-1.1.1-notes.html
The text version has the updates correctly appearing in the 1.1.0 notes file: https://www.openssl.org/news/cl110.txt

I'm not sure how to submit a pull request for this problem because the source files do not appear to be in this repository.

**Comment by levitte** [comment]
Ok, you're mixing things up a bit...  https://www.openssl.org/news/openssl-1.1.1-notes.inc is based on [NEWS](https://github.com/openssl/openssl/blob/master/NEWS), while https://www.openssl.org/news/cl110.txt is based on [CHANGES](https://github.com/openssl/openssl/blob/master/CHANGES).

With that knowledge, do you still think there's a formatting error?  In that case, please show us specifics.

**Comment by jrchamp** [comment]
The second-to-last bullet merges the title from the new 1.1.0h updates into the last bullet from the 1.1.1 updates

"Grand redesign of the OpenSSL random generator Major changes between OpenSSL 1.1.0g and OpenSSL 1.1.0h [under development]"

**Comment by jrchamp** [comment]
To be clear: the NEWS file looks fine. The new unreleased section is placed into the wrong generated file and is not marked as a header. Perhaps the NEWS file parser is the cause?

**Comment by levitte** [comment]
This is kind of a philosophical question.  It's true that `Major changes ...` shouldn't appear.  *however*, since 1.1.0h hasn't been release yet and the 1.1.0g to 1.1.0h changes are also present in 1.1.1-pre, it's perfectly correct that they get included in this note, especially since the title specifically says "between OpenSSL 1.1.0g and OpenSSL 1.1.1".

But yeah, that other `Major.... ` shouldn't have been included.

I'll have a look at your PR

**Comment by iamamoose** [comment]
pr was merged
